# Generated by Django 3.2.20 on 2023-08-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(help_text='Name of the person at this address', max_length=80),
        ),
    ]
