# Generated by Django 3.2.20 on 2023-08-21 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.EmailField(help_text='Reply to your customer at this address.', max_length=254)),
                ('query', models.CharField(help_text='Please outline your query for us in less than 400 characters.', max_length=400)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('replied', models.BooleanField(default=False, help_text=('Keep track of which customer queries you have replied to.',))),
            ],
            options={
                'verbose_name_plural': 'Customer queries',
            },
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'FAQ'},
        ),
        migrations.AlterField(
            model_name='faq',
            name='published',
            field=models.BooleanField(default=True, help_text='Mark as published to make the FAQ visible on the site.'),
        ),
    ]
