# Generated by Django 3.2.20 on 2023-08-21 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_auto_20230821_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerquery',
            name='resolved',
            field=models.BooleanField(default=False, help_text='Mark as resolved when your customer query has been dealt with.'),
        ),
        migrations.AlterField(
            model_name='customerquery',
            name='query',
            field=models.CharField(help_text='Please outline your query in less than 1000 characters.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='customerquery',
            name='replied',
            field=models.BooleanField(default=False, help_text='Keep track of which customer queries you have replied to.'),
        ),
    ]
