# Generated by Django 3.2.20 on 2023-08-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='a@b.com', max_length=255),
            preserve_default=False,
        ),
    ]
