# Generated by Django 3.2.20 on 2023-08-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20230807_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='./static/images/no-photo.png', upload_to=''),
        ),
    ]
