# Generated by Django 3.2.20 on 2023-08-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20230823_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('Sealed', 'Sealed'), ('Like New', 'Like New'), ('Very Good', 'Very Good'), ('Good', 'Good'), ('Acceptable', 'Acceptable')], default='Very Good', max_length=20),
        ),
    ]
