# Generated by Django 3.2.20 on 2023-08-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20230823_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='visible',
            field=models.BooleanField(default=True, help_text='Select to make the product visible on the site. This can be unchecked to stop sold out products from appearing on the site.'),
        ),
    ]
